### ISSUE TITLE
Open source build instructions or source codes?

### ISSUE THREAD

**Issue by sdcb** [AvenSun/OpenCvSharpSlim#3]
It's a pretty good idea that make OpenCV smaller

**Comment by AvenSun** [comment]
hi @sdcb 

thank you for your question.
actually OpenCvSharpSlim runtime is compiled by me manually.
I'm not good at powershell or shell. that's the main reason I didn't make this automation. 
but It's not tough if you wanna build your own.
the main step is just like what I said in [readme](https://github.com/AvenSun/OpenCvSharpSlim#build-other-platform).

1. build you own OpenCv static library or pick up one from [OpenCvSlim](https://github.com/AvenSun/OpenCvSlim).
2. supposing you chose the package of [OpenCvSlim-4.8.1-win-vs2019.zip](https://github.com/AvenSun/OpenCvSlim/blob/master/OpenCvSlim-4.8.1-win-vs2019.zip). 
3. download and extract Zip to **opencv_files** in the root of  **OpenCvSharp** solution
4. it looks like below.

```
OpenCvSharp
------opencv_files
-----------x64
--------------include
--------------x64
--------------OpenCVConfig.cmake
--------------OpenCVConfig-version.cmake
--------------setup_vars_opencv4.cmd
-----------x86
--------------include
--------------x64
--------------OpenCVConfig.cmake
--------------OpenCVConfig-version.cmake
--------------setup_vars_opencv4.cmd
```
                       
5. then you should modify some include path of project **OpenCvSharpExtern**
![opencvsharpslim](https://github.com/AvenSun/OpenCvSharpSlim/assets/5615543/9567debd-d854-4e13-87d4-2812a1cb5789)

7. delete all unused modules from project **OpenCvSharpExtern**, just keep modules you chose when compiled OpenCv library. this step is kinda difficult.
![modules](https://github.com/AvenSun/OpenCvSharpSlim/assets/5615543/d3540fc3-c244-4a98-84b9-6684375509c8)

9. you can try build project **OpenCvSharpExtern** after  clean up unused modules.

other platform is roughly the same. 
the main difference is we need set OpenCv include path in **CMakeLists.txt**.
or we can pass it to **Cmake** via **Cmake** options.
you can have a try.

**Comment by sdcb** [comment]
good to know, thanks.
